kind: pipeline
name: default

clone:
  depth: 50

steps:
  - name: publish
    image: plugins/docker
    settings:
      file: Dockerfile
      registry: 192.168.50.5
      insecure: true
      repo: 192.168.50.5/drone_ci_app
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: 192.168.50.5/deploy
    pull: always
    settings:
      become: true
      playbook: /root/.ansible/playbooks/deploy.yml
      inventory: /root/.ansible/environments/hosts
      private_key:
        from_secret: ansible_private_key
      verbose: 4

  # - name: notify
  #   image: appleboy/drone-telegram
  #   settings:
  #     token: 818734516:AAG-Y--OaOeZeML6blEgLlHwZFmO3gQ3bYY
  #     to: 278122002

image_pull_secrets:
- dockerconfigjson